---
development:
  cloud_name: e71az
  api_key: '327857726899143'
  api_secret: lkgCoRGXibrzPjjcO6jiPvjdVfA
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: e71az
  api_key: '327857726899143'
  api_secret: lkgCoRGXibrzPjjcO6jiPvjdVfA
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: e71az
  api_key: '327857726899143'
  api_secret: lkgCoRGXibrzPjjcO6jiPvjdVfA
  enhance_image_tag: true
  static_file_support: false
